# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('locationKey', models.IntegerField(primary_key=True, serialize=False)),
                ('locName', models.CharField(max_length=100)),
                ('oLangKey', models.IntegerField()),
                ('locNameOL', models.CharField(max_length=100)),
                ('extraInfo', models.CharField(max_length=100)),
                ('notes', models.TextField()),
                ('creationDate', models.DateTimeField()),
                ('tstamp', django_unixdatetimefield.fields.UnixDateTimeField()),
            ],
            options={
                'db_table': 'location',
            },
        ),
    ]
