# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_auto_20160309_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='oLangKey',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
