# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0003_auto_20160309_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='locationKey',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='oLangKey',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='tstamp',
            field=django_unixdatetimefield.fields.UnixDateTimeField(auto_now=True),
        ),
    ]
