# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0006_auto_20160309_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='osm_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='queryName',
            field=models.CharField(default='', max_length=100),
        ),
    ]
